import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1788809617079 implements MigrationInterface {
    name = 'InitialSchema1788809617079'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('platform_admin', 'school_admin', 'teacher', 'student', 'parent', 'support_agent')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'disabled', 'pending_consent')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying, "phone" character varying, "passwordHash" character varying, "role" "public"."users_role_enum" NOT NULL, "schoolId" character varying, "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "lastLoginAt" TIMESTAMP WITH TIME ZONE, "failedLoginAttempts" integer NOT NULL DEFAULT '0', "lockedUntil" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e2dd77cb8a46c78d8ea34de039" ON "users" ("email") WHERE "email" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_875541f7dbe1b8565414f9f80b" ON "users" ("phone") WHERE "phone" IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "badges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "emoji" character varying NOT NULL, "label" character varying NOT NULL, "code" character varying NOT NULL, CONSTRAINT "UQ_48fe47e292737e09162b08c4f7c" UNIQUE ("code"), CONSTRAINT "PK_8a651318b8de577e8e217676466" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."packages_cycle_enum" AS ENUM('monthly', 'quarterly', 'annual')`);
        await queryRunner.query(`CREATE TABLE "packages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "price" integer NOT NULL, "cycle" "public"."packages_cycle_enum" NOT NULL, "maxStudents" integer NOT NULL, "maxClasses" integer NOT NULL, "storageGB" integer NOT NULL, "color" character varying NOT NULL, "features" text array NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_020801f620e21f943ead9311c98" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "school_contacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "schoolId" uuid NOT NULL, "name" character varying NOT NULL, "role" character varying NOT NULL, "phone" character varying NOT NULL, "email" character varying NOT NULL, CONSTRAINT "PK_c8addc29c4106a2e574dffd0e73" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "school_approvals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "schoolId" uuid NOT NULL, "parentName" character varying NOT NULL, "studentName" character varying NOT NULL, "note" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a0e7756650a8d55d847cf3816e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."schools_status_enum" AS ENUM('active', 'renewal_due', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "schools" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "city" character varying NOT NULL, "type" character varying NOT NULL, "principal" character varying NOT NULL, "status" "public"."schools_status_enum" NOT NULL DEFAULT 'active', "packageId" uuid, "joinedAt" date NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_95b932e47ac129dd8e23a0db548" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."teachers_status_enum" AS ENUM('active', 'disabled')`);
        await queryRunner.query(`CREATE TYPE "public"."teachers_source_enum" AS ENUM('manual', 'csv', 'self_enrolled')`);
        await queryRunner.query(`CREATE TABLE "teachers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "schoolId" uuid NOT NULL, "userId" character varying, "name" character varying NOT NULL, "specialty" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying NOT NULL, "status" "public"."teachers_status_enum" NOT NULL DEFAULT 'active', "source" "public"."teachers_source_enum" NOT NULL DEFAULT 'manual', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a8d4f83be3abe4c687b0a0093c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."support_conversations_status_enum" AS ENUM('open', 'closed')`);
        await queryRunner.query(`CREATE TABLE "support_conversations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "participantId" uuid NOT NULL, "agentId" uuid, "status" "public"."support_conversations_status_enum" NOT NULL DEFAULT 'open', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6647be672020591c574a98089e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."students_source_enum" AS ENUM('manual', 'csv', 'self_enrolled')`);
        await queryRunner.query(`CREATE TABLE "students" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "schoolId" uuid NOT NULL, "userId" character varying, "parentUserId" character varying, "classId" character varying, "name" character varying NOT NULL, "stage" character varying NOT NULL DEFAULT 'غير محدد', "parentName" character varying, "parentEmail" character varying, "studentEmail" character varying, "source" "public"."students_source_enum" NOT NULL DEFAULT 'manual', "points" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d7f07271ad4ce999880713f05e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "support_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversationId" uuid NOT NULL, "senderId" uuid NOT NULL, "text" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2aa37479e71ef29cbf4dba2b1a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "platform_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "platformName" character varying NOT NULL DEFAULT 'ألف المستقبل', "officialEmail" character varying, "logoUrl" character varying, "security" jsonb NOT NULL DEFAULT '{}', "agora" jsonb NOT NULL DEFAULT '{}', "smtp" jsonb NOT NULL DEFAULT '{}', "sms" jsonb NOT NULL DEFAULT '{}', "storageAutoCleanup" boolean NOT NULL DEFAULT false, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2934aeb70ec285196dcab4a2e96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pdf_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "storageUrl" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2e4c061b9161712a40c2cfc33fa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."resources_stage_enum" AS ENUM('ابتدائي', 'متوسط', 'ثانوي')`);
        await queryRunner.query(`CREATE TYPE "public"."resources_status_enum" AS ENUM('draft', 'published', 'archived')`);
        await queryRunner.query(`CREATE TABLE "resources" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "subject" character varying NOT NULL, "stage" "public"."resources_stage_enum" NOT NULL, "program" character varying NOT NULL, "description" text NOT NULL, "sessionsCount" integer NOT NULL DEFAULT '0', "questionsIncluded" integer NOT NULL DEFAULT '0', "contentItemsIncluded" integer NOT NULL DEFAULT '0', "requiredFeature" character varying NOT NULL, "color" character varying NOT NULL, "status" "public"."resources_status_enum" NOT NULL DEFAULT 'draft', "versionNumber" integer NOT NULL DEFAULT '1', "schoolsUsingCount" integer NOT NULL DEFAULT '0', "totalStudentsCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_632484ab9dff41bba94f9b7c85e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."school_invoices_status_enum" AS ENUM('paid', 'pending', 'overdue')`);
        await queryRunner.query(`CREATE TABLE "school_invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "schoolId" uuid NOT NULL, "issuedAt" date NOT NULL, "amount" integer NOT NULL, "status" "public"."school_invoices_status_enum" NOT NULL DEFAULT 'pending', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6e5f2abe51d7a585979e0999c5c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "class_meetings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "classId" uuid NOT NULL, "title" character varying NOT NULL, "date" date NOT NULL, "time" character varying NOT NULL, "meetingId" uuid, CONSTRAINT "PK_0f8d7319fbd7da909a89ca75690" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."classes_status_enum" AS ENUM('preparing', 'active', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "classes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "schoolId" uuid NOT NULL, "resourceId" uuid, "resourceVersionAtGeneration" integer, "name" character varying NOT NULL, "teacherId" uuid, "studentsCount" integer NOT NULL DEFAULT '0', "color" character varying NOT NULL, "performance" integer NOT NULL DEFAULT '0', "status" "public"."classes_status_enum" NOT NULL DEFAULT 'preparing', "autoAgora" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e207aa15404e9b2ce35910f9f7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."meetings_status_enum" AS ENUM('scheduled', 'live', 'ended')`);
        await queryRunner.query(`CREATE TABLE "meetings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "classId" uuid NOT NULL, "title" character varying NOT NULL, "scheduledAt" TIMESTAMP WITH TIME ZONE NOT NULL, "durationMinutes" integer NOT NULL, "status" "public"."meetings_status_enum" NOT NULL DEFAULT 'scheduled', "agoraChannelName" character varying, "sessionPlanBlockIds" uuid array NOT NULL DEFAULT '{}', "pushedActivityBlockId" character varying, "completedAt" TIMESTAMP WITH TIME ZONE, "completionChecklist" jsonb, "completionRating" integer, "completionNote" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_aa73be861afa77eb4ed31f3ed57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."attendance_records_status_enum" AS ENUM('present', 'absent')`);
        await queryRunner.query(`CREATE TABLE "attendance_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "studentId" uuid NOT NULL, "meetingId" uuid NOT NULL, "status" "public"."attendance_records_status_enum" NOT NULL, "reason" text, CONSTRAINT "PK_946920332f5bc9efad3f3023b96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recordings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "meetingId" uuid NOT NULL, "title" character varying NOT NULL, "playbackUrl" character varying NOT NULL, "durationSeconds" integer NOT NULL DEFAULT '0', "views" integer NOT NULL DEFAULT '0', "sizeBytes" bigint NOT NULL DEFAULT '0', "isPublic" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_e7356dffef7cbdbba112d54ff1" UNIQUE ("meetingId"), CONSTRAINT "PK_8c3247d5ee4551d59bb2115a484" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "program_days" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "resourceId" uuid NOT NULL, "dayNumber" integer NOT NULL, "title" character varying NOT NULL, CONSTRAINT "PK_cff1cb768e103fd904e79baf3e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "program_units" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "dayId" uuid NOT NULL, "unitNumber" integer NOT NULL, "title" character varying NOT NULL, CONSTRAINT "PK_248186fe916cd0b7099b472d9bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "program_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "unitId" uuid NOT NULL, "sessionNumber" integer NOT NULL, "title" character varying NOT NULL, "durationMinutes" integer NOT NULL, CONSTRAINT "PK_e3ceb0981899cdf727f81dd487d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "title" character varying NOT NULL, "subtitle" character varying NOT NULL, "iconBody" character varying NOT NULL DEFAULT '🔔', "iconColor" character varying NOT NULL DEFAULT '#4338F2', "read" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."content_blocks_type_enum" AS ENUM('lecture', 'activity')`);
        await queryRunner.query(`CREATE TYPE "public"."content_blocks_executionmode_enum" AS ENUM('فردي', 'جماعي', 'ثنائي')`);
        await queryRunner.query(`CREATE TYPE "public"."content_blocks_deliverychannel_enum" AS ENUM('trainer_guide_only', 'shared_live_screen', 'student_synchronous', 'student_async_homework')`);
        await queryRunner.query(`CREATE TABLE "content_blocks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sessionId" uuid NOT NULL, "type" "public"."content_blocks_type_enum" NOT NULL, "title" character varying NOT NULL, "durationMinutes" integer NOT NULL, "executionMode" "public"."content_blocks_executionmode_enum", "deliveryChannel" "public"."content_blocks_deliverychannel_enum", "activityType" character varying, "instructionsText" text, "materialsNeeded" text, "trainerNotes" text, "position" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_607a3abb7e7af9bb5c22090a597" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."enrollment_codes_codetype_enum" AS ENUM('single', 'multi', 'batch')`);
        await queryRunner.query(`CREATE TYPE "public"."enrollment_codes_status_enum" AS ENUM('active', 'expired', 'disabled')`);
        await queryRunner.query(`CREATE TABLE "enrollment_codes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "schoolId" uuid NOT NULL, "classId" character varying NOT NULL, "codeType" "public"."enrollment_codes_codetype_enum" NOT NULL, "maxUses" integer NOT NULL, "currentUses" integer NOT NULL DEFAULT '0', "expiresAt" date NOT NULL, "status" "public"."enrollment_codes_status_enum" NOT NULL DEFAULT 'active', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_bf46324a1ddae6b60bc214771c8" UNIQUE ("code"), CONSTRAINT "PK_1cb09f5a923989689352cd109a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."content_items_type_enum" AS ENUM('video', 'pdf', 'image', 'activity')`);
        await queryRunner.query(`CREATE TABLE "content_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "type" "public"."content_items_type_enum" NOT NULL, "sizeBytes" bigint NOT NULL DEFAULT '0', "storageUrl" character varying NOT NULL, "color" character varying NOT NULL, "folder" character varying NOT NULL, "tags" text array NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9c6bf4f28851752cee186915e39" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."assignments_kind_enum" AS ENUM('quiz', 'essay', 'puzzle')`);
        await queryRunner.query(`CREATE TABLE "assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "classId" uuid NOT NULL, "blockId" uuid, "title" character varying NOT NULL, "kind" "public"."assignments_kind_enum" NOT NULL, "dueAt" TIMESTAMP WITH TIME ZONE NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c54ca359535e0012b04dcbd80ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."submissions_status_enum" AS ENUM('in_progress', 'submitted', 'late', 'graded')`);
        await queryRunner.query(`CREATE TABLE "submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "assignmentId" uuid NOT NULL, "studentId" uuid NOT NULL, "status" "public"."submissions_status_enum" NOT NULL DEFAULT 'in_progress', "answerPayload" jsonb, "submittedAt" TIMESTAMP WITH TIME ZONE, "grade" integer, "gradedAt" TIMESTAMP WITH TIME ZONE, "teacherNote" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_10b3be95b8b2fb1e482e07d706b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "auto_message_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "channel" character varying NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "body" text NOT NULL, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8f71017764f922085b69e67be89" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "otp_codes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "phone" character varying NOT NULL, "codeHash" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "attempts" integer NOT NULL DEFAULT '0', "consumed" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9d0487965ac1837d57fec4d6a26" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "tokenHash" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "revoked" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c25bc63d248ca90e8dcc1d92d0" ON "refresh_tokens" ("tokenHash") `);
        await queryRunner.query(`CREATE TYPE "public"."activity_log_tone_enum" AS ENUM('success', 'warning', 'danger', 'indigo')`);
        await queryRunner.query(`CREATE TABLE "activity_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "actorName" character varying NOT NULL, "actorUserId" character varying, "action" character varying NOT NULL, "target" character varying NOT NULL, "ip" character varying, "tone" "public"."activity_log_tone_enum" NOT NULL DEFAULT 'indigo', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_067d761e2956b77b14e534fd6f1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "student_badges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "studentId" uuid NOT NULL, "badgeId" uuid NOT NULL, "earnedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_89c04a467227c27372fd7d22b95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "school_contacts" ADD CONSTRAINT "FK_55e4f60fd5fe99a821c26ffb696" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "school_approvals" ADD CONSTRAINT "FK_f2ec8004bedf293cb9e88b1c41f" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schools" ADD CONSTRAINT "FK_5f7488ab2e057fa45b5e14ea81a" FOREIGN KEY ("packageId") REFERENCES "packages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teachers" ADD CONSTRAINT "FK_20a4e9c68d652b6a329b08e09cb" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support_conversations" ADD CONSTRAINT "FK_73e5abee3e5a08bdbe63360232b" FOREIGN KEY ("participantId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support_conversations" ADD CONSTRAINT "FK_91535536fc6b2c494abb2208ad2" FOREIGN KEY ("agentId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_44855579fce3690c57ae8b12999" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support_messages" ADD CONSTRAINT "FK_e070973586504df3c9b03e9e4d0" FOREIGN KEY ("conversationId") REFERENCES "support_conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support_messages" ADD CONSTRAINT "FK_a6d023327205aee297257d4f0fe" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "school_invoices" ADD CONSTRAINT "FK_441c84d160e36f82c81ac66e6df" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_meetings" ADD CONSTRAINT "FK_a702c59651860dd79fabae13cf5" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_meetings" ADD CONSTRAINT "FK_176041cc6dd224a7a0bac886661" FOREIGN KEY ("meetingId") REFERENCES "meetings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_17d36b6f6a79669ba76b671ac72" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_02f7ca4d725ab2aa12870eaed5e" FOREIGN KEY ("resourceId") REFERENCES "resources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_4b7ac7a7eb91f3e04229c7c0b6f" FOREIGN KEY ("teacherId") REFERENCES "teachers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meetings" ADD CONSTRAINT "FK_140921c714d6c495624815b8dc9" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_21f6cf258d12a2432bd2a8f798d" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_a3bdef3a839e9ca6e8364006335" FOREIGN KEY ("meetingId") REFERENCES "meetings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recordings" ADD CONSTRAINT "FK_e7356dffef7cbdbba112d54ff1c" FOREIGN KEY ("meetingId") REFERENCES "meetings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "program_days" ADD CONSTRAINT "FK_20b022a04eeb0196d470862c772" FOREIGN KEY ("resourceId") REFERENCES "resources"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "program_units" ADD CONSTRAINT "FK_7e345abb13133324b9a7bfef4e5" FOREIGN KEY ("dayId") REFERENCES "program_days"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "program_sessions" ADD CONSTRAINT "FK_8040e79af265e5c1a64cc0ae714" FOREIGN KEY ("unitId") REFERENCES "program_units"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content_blocks" ADD CONSTRAINT "FK_d332c15504ea575e2bdec627008" FOREIGN KEY ("sessionId") REFERENCES "program_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollment_codes" ADD CONSTRAINT "FK_82f74fed9a6591bdd84681dcaf2" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_c5382064b68e93e2ac371de898e" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_bc2a90d49f3d4d34f24dc96ff27" FOREIGN KEY ("blockId") REFERENCES "content_blocks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD CONSTRAINT "FK_c2611c601f49945ceff5c0909a2" FOREIGN KEY ("assignmentId") REFERENCES "assignments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD CONSTRAINT "FK_4fc99318a291abd7e2a50f50851" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_badges" ADD CONSTRAINT "FK_0b45c7a8f7199cb10b6de96c361" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_badges" ADD CONSTRAINT "FK_8d28f7fb5afc5ad951822e9b0fe" FOREIGN KEY ("badgeId") REFERENCES "badges"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "student_badges" DROP CONSTRAINT "FK_8d28f7fb5afc5ad951822e9b0fe"`);
        await queryRunner.query(`ALTER TABLE "student_badges" DROP CONSTRAINT "FK_0b45c7a8f7199cb10b6de96c361"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "FK_4fc99318a291abd7e2a50f50851"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "FK_c2611c601f49945ceff5c0909a2"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_bc2a90d49f3d4d34f24dc96ff27"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_c5382064b68e93e2ac371de898e"`);
        await queryRunner.query(`ALTER TABLE "enrollment_codes" DROP CONSTRAINT "FK_82f74fed9a6591bdd84681dcaf2"`);
        await queryRunner.query(`ALTER TABLE "content_blocks" DROP CONSTRAINT "FK_d332c15504ea575e2bdec627008"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "program_sessions" DROP CONSTRAINT "FK_8040e79af265e5c1a64cc0ae714"`);
        await queryRunner.query(`ALTER TABLE "program_units" DROP CONSTRAINT "FK_7e345abb13133324b9a7bfef4e5"`);
        await queryRunner.query(`ALTER TABLE "program_days" DROP CONSTRAINT "FK_20b022a04eeb0196d470862c772"`);
        await queryRunner.query(`ALTER TABLE "recordings" DROP CONSTRAINT "FK_e7356dffef7cbdbba112d54ff1c"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_a3bdef3a839e9ca6e8364006335"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_21f6cf258d12a2432bd2a8f798d"`);
        await queryRunner.query(`ALTER TABLE "meetings" DROP CONSTRAINT "FK_140921c714d6c495624815b8dc9"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_4b7ac7a7eb91f3e04229c7c0b6f"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_02f7ca4d725ab2aa12870eaed5e"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_17d36b6f6a79669ba76b671ac72"`);
        await queryRunner.query(`ALTER TABLE "class_meetings" DROP CONSTRAINT "FK_176041cc6dd224a7a0bac886661"`);
        await queryRunner.query(`ALTER TABLE "class_meetings" DROP CONSTRAINT "FK_a702c59651860dd79fabae13cf5"`);
        await queryRunner.query(`ALTER TABLE "school_invoices" DROP CONSTRAINT "FK_441c84d160e36f82c81ac66e6df"`);
        await queryRunner.query(`ALTER TABLE "support_messages" DROP CONSTRAINT "FK_a6d023327205aee297257d4f0fe"`);
        await queryRunner.query(`ALTER TABLE "support_messages" DROP CONSTRAINT "FK_e070973586504df3c9b03e9e4d0"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_44855579fce3690c57ae8b12999"`);
        await queryRunner.query(`ALTER TABLE "support_conversations" DROP CONSTRAINT "FK_91535536fc6b2c494abb2208ad2"`);
        await queryRunner.query(`ALTER TABLE "support_conversations" DROP CONSTRAINT "FK_73e5abee3e5a08bdbe63360232b"`);
        await queryRunner.query(`ALTER TABLE "teachers" DROP CONSTRAINT "FK_20a4e9c68d652b6a329b08e09cb"`);
        await queryRunner.query(`ALTER TABLE "schools" DROP CONSTRAINT "FK_5f7488ab2e057fa45b5e14ea81a"`);
        await queryRunner.query(`ALTER TABLE "school_approvals" DROP CONSTRAINT "FK_f2ec8004bedf293cb9e88b1c41f"`);
        await queryRunner.query(`ALTER TABLE "school_contacts" DROP CONSTRAINT "FK_55e4f60fd5fe99a821c26ffb696"`);
        await queryRunner.query(`DROP TABLE "student_badges"`);
        await queryRunner.query(`DROP TABLE "activity_log"`);
        await queryRunner.query(`DROP TYPE "public"."activity_log_tone_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c25bc63d248ca90e8dcc1d92d0"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "otp_codes"`);
        await queryRunner.query(`DROP TABLE "auto_message_templates"`);
        await queryRunner.query(`DROP TABLE "submissions"`);
        await queryRunner.query(`DROP TYPE "public"."submissions_status_enum"`);
        await queryRunner.query(`DROP TABLE "assignments"`);
        await queryRunner.query(`DROP TYPE "public"."assignments_kind_enum"`);
        await queryRunner.query(`DROP TABLE "content_items"`);
        await queryRunner.query(`DROP TYPE "public"."content_items_type_enum"`);
        await queryRunner.query(`DROP TABLE "enrollment_codes"`);
        await queryRunner.query(`DROP TYPE "public"."enrollment_codes_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."enrollment_codes_codetype_enum"`);
        await queryRunner.query(`DROP TABLE "content_blocks"`);
        await queryRunner.query(`DROP TYPE "public"."content_blocks_deliverychannel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."content_blocks_executionmode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."content_blocks_type_enum"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "program_sessions"`);
        await queryRunner.query(`DROP TABLE "program_units"`);
        await queryRunner.query(`DROP TABLE "program_days"`);
        await queryRunner.query(`DROP TABLE "recordings"`);
        await queryRunner.query(`DROP TABLE "attendance_records"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_records_status_enum"`);
        await queryRunner.query(`DROP TABLE "meetings"`);
        await queryRunner.query(`DROP TYPE "public"."meetings_status_enum"`);
        await queryRunner.query(`DROP TABLE "classes"`);
        await queryRunner.query(`DROP TYPE "public"."classes_status_enum"`);
        await queryRunner.query(`DROP TABLE "class_meetings"`);
        await queryRunner.query(`DROP TABLE "school_invoices"`);
        await queryRunner.query(`DROP TYPE "public"."school_invoices_status_enum"`);
        await queryRunner.query(`DROP TABLE "resources"`);
        await queryRunner.query(`DROP TYPE "public"."resources_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."resources_stage_enum"`);
        await queryRunner.query(`DROP TABLE "pdf_templates"`);
        await queryRunner.query(`DROP TABLE "platform_settings"`);
        await queryRunner.query(`DROP TABLE "support_messages"`);
        await queryRunner.query(`DROP TABLE "students"`);
        await queryRunner.query(`DROP TYPE "public"."students_source_enum"`);
        await queryRunner.query(`DROP TABLE "support_conversations"`);
        await queryRunner.query(`DROP TYPE "public"."support_conversations_status_enum"`);
        await queryRunner.query(`DROP TABLE "teachers"`);
        await queryRunner.query(`DROP TYPE "public"."teachers_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."teachers_status_enum"`);
        await queryRunner.query(`DROP TABLE "schools"`);
        await queryRunner.query(`DROP TYPE "public"."schools_status_enum"`);
        await queryRunner.query(`DROP TABLE "school_approvals"`);
        await queryRunner.query(`DROP TABLE "school_contacts"`);
        await queryRunner.query(`DROP TABLE "packages"`);
        await queryRunner.query(`DROP TYPE "public"."packages_cycle_enum"`);
        await queryRunner.query(`DROP TABLE "badges"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_875541f7dbe1b8565414f9f80b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e2dd77cb8a46c78d8ea34de039"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
    }

}
